name: fife_image
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  image: ^4.2.0
  file_picker: ^8.0.6
  logger: ^2.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cross_file: ^0.3.4+1
  dio: ^5.5.0+1
  path: ^1.9.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_tex: ^4.0.6
  flutter_markdown: ^0.7.3+1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  # todo this is the problem: riverpod_lint: ^2.3.12
  json_serializable: ^6.9.0
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/
