import 'package:flutter/material.dart';

const server = 'http://127.0.0.1:5000/';
const serverPath = 'server/dist/main';
const bgTag = 'bg_correct';
const convexHullTag = 'convex_hull';
const infiltrationTag = 'custom_infiltration';
const tags = [bgTag, convexHullTag, infiltrationTag];
const cd4 = 'CD4';
const cd8 = 'CD8';
const glucagon = 'Glucagon';
const insulin = 'Insulin';
const pdl1 = 'PD-L1';
const overlay = 'overlay';
const lengthScale = 'um';
const totalChannelNumber = 5;
const defaultPixelSize = 0.5;
const defaultCellSize = 150.0;
const kTitleStyle = TextStyle(fontSize: 28.0);
const kSubtitleStyle = TextStyle(fontSize: 22.0);
const kTextStyle = TextStyle(color: Colors.white);
const kLinkStyle = TextStyle(color: Colors.blue);
const proteins = [cd4, glucagon, insulin, cd8, pdl1];
const kParagraphSpacing = 16.0;
const kBottomSpacer = 200.0;